### ISSUE TITLE
好友功能

### ISSUE THREAD

**Issue by StudyDogs** [pengpengno/IFxIM#8]
1、采用redis的String存放好友列表数据。每次登录会进行初始化将用户列表放入本地内存，

后续各种操作优先操作本地内存 然后异步做redis处理。

2、采用redis的set存放用户关系（主要用于共同好友推荐)，以用户id为key 好友id为value

**Comment by pengpengno** [comment]
上述实现方案1 可执行，2 中用于存放用户关系的 这个set 是否会因为好友关系网的复杂而过重？

### 好友涉及功能
1.好友申请的收发
2. 黑名单？ （是否归属好友模块）
3. 好友搜索

**Comment by StudyDogs** [comment]
哪有那么多好友，qq\微信不也就几百人
1、黑名单设置用户字段就行
2、搜索本地内存上对好友列表做过滤
**问题：**
如何搜索用户并添加好友。
是否建立用户库，将用户ip、端口以及基本信息入库。搜索根据昵称、id去查找获取到对应用户的ip和端口？

**Comment by pengpengno** [comment]
###
上述建议1，2 可行，设想合理
### 问题discuss
##### 如何搜索用户并添加好友
好友的搜索功能是一种全局搜索能力,两种方案
1. 实现可以支持 消息 、会话、群组 等高维的搜索（此处可能需要接入中间件，设计有难度，值得挑战）
2. 简单的DB用户搜索， redis 查看在线状态 ，继而通过```netty```channel 是否存在 来做在线or离线消息
##### 如何搜索用户并添加好友....
用户不应直接与ip 端口，如果存在场景需要 建议使用**中间代理实体的模式**来实现 比如 创建**用户动态网络信息实体**，个人任务网络环境信息非 用户检索的可靠条件

**Comment by StudyDogs** [comment]
我的设想是这样：
已有用户库，且搜索db现阶段不是很大，可以直接用昵称或者账号去查询db
根据用户id去es找申请人的信息(用户昵称 签名 头像 ip 端口)，展示出来(隐藏ip和端口)
选择添加，记录该条申请信息，同时需要一个mq，将消息推送
1、如果用户在线
直接根据ip、端口推送到客户端。同时修改该申请记录状态
2、用户离线
用户登录可以拉取该申请表中未同意(拒绝)的记录
**问题**
申请信息是入db还是存入redis？

**Comment by pengpengno** [comment]
不用纠结Ip 
### netty简介及否定ip绑定用户的原因
NIO的通信异步框架，主要通信实体为chanel  ，chanel 贯彻netty通信的整个生命周期， 在netty的设计中存在大量回调，执行链的设计，在netty client 端链接server 后，可以为两端之间的chanel 设置绑定值， 比如accountId， 形成<k,v><账户业务信息，channel>；离线需要通过 订阅的模式设计；
### 结论
1. 不建议 ip->绑定用户的 设计 ，推荐使用account->channel的方式
#### 申请信息是入db还是存入redis？
> 申请信息的存储层进入db理由 

长期不上线的情况下，
redis中的数据如果删除，则会造成业务丢失，
不删除则成了虚消息（长期时间段内无法确定被消费的时间点）

> 关于消息系统

这是IM系统中的核心之一 ，需要深入研究， 所以好友系统不应 照着未来的消息系统来兼容 来妥协；保持高度解耦，
抽象的来看关于申请好友这个功能，无非就是  A->B message 

目前设想消息系统的主要能力
1. 收发信箱的抽象存储概念
2. 在线推送
3. 离线存储
4. 订阅的消息消费模式
5. 读写扩散混合全场景兼容（单聊建议写扩散，群聊建议读扩散）

下图 简述了两种模式 ，配置文章看， 读懂后就理解了
![image](https://user-images.githubusercontent.com/48426117/184316647-08c697ba-9697-49d6-b50a-cc4af4561de2.png)
![image](https://user-images.githubusercontent.com/48426117/184316655-42b57147-6ec3-4e53-8f13-a8d5623ed103.png)

参考 相关文章 [IM开发干货分享：浅谈IM系统中离线消息、历史消息的最佳实践](http://www.52im.net/thread-3887-1-1.html)

**Comment by pengpengno** [comment]
## 好友关系的设计更新
### 目标
实现无好友关系的IM ，通讯请求可直接发起。 所以 为了避免 不存在好友关系而导致刷新后的信息丢失，使用**会话**概念来处理两端之间的通讯业务；
feat：提供并实现**会话**能力
