### ISSUE TITLE
关于 token 再CS 体系中的应用

### ISSUE THREAD

**Issue by pengpengno** [pengpengno/IFxIM#9]
### token 
希望再通信协议中加入jwt 用于后台接口校验
#### 问题
@StudyDogs 
> 而且现在有个问题 token基本上是基于web应用的 现在如果不走web应用只能写过滤器或者写aop拦截了

aop再整个后台体系中的拦截level 是比较高层，希望能使用较为基层的拦截手段

**Comment by StudyDogs** [comment]
咋拦截？用Filter？这个拦截究竟再服务端还是再业务层

**Comment by pengpengno** [comment]
其实对于在 C/S 体系中使用JWT 来进行身份识别认证 ，持保留意见， 因为没有看到过其他类似的IM产品，有去实现这个事情， 使用JWT来身份认证也是由于web开发 BS的架构下，所有链接都是无状态的短链接 所以才需要JWT 认证， 对于长链接的CS 为链接赋予状态是否有些 生搬硬套？， 因为客户端 在 【信道】（与服务端 目标主机 的链接通道）正常工作的情况下，所有请求都是 有状态的，增加JWT 的意义没有那么明显；

**Comment by pengpengno** [comment]
> 咋拦截？用Filter？这个拦截究竟再服务端还是再业务层
拦截是服务段

**Comment by StudyDogs** [comment]
。。。。没有意义说啥jwt

**Comment by pengpengno** [comment]
好吧  issue close  真是一次 无意义的 issue。思考的简单了
